import {
  Project,
  Task,
  TaskStatus,
  TaskPriority,
} from "@/app/projects/[id]/types";

const now = new Date();

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Project Management App",
    description: "A comprehensive project management application",
    logo: "/project-management-logo.png",
    isMain: true,
    viewed: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    name: "Task Tracker",
    description: "Simple task tracking application",
    logo: "/task-tracker-logo.png",
    isMain: false,
    viewed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    name: "Team Collaboration Tool",
    description: "Tool for team collaboration and communication",
    logo: "/team-collab-logo.png",
    isMain: false,
    viewed: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Design User Interface",
    description: "Create wireframes and mockups for the main dashboard",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    checklistItems: [
      {
        id: "1-1",
        title: "Wireframes",
        text: "Create wireframes for dashboard",
        completed: true,
        taskId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "1-2",
        title: "Mockups",
        text: "Create high-fidelity mockups",
        completed: false,
        taskId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    title: "Implement Authentication",
    description: "Set up user authentication with NextAuth.js",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    projectId: "1",
    plannedDate: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000), // 5 days in future
    checklistItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Optimize Images",
    description: "Optimize all images for better performance",
    status: TaskStatus.DONE,
    priority: TaskPriority.LOW,
    projectId: "1",
    plannedDate: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    checklistItems: [
      {
        id: "5",
        title: "Compress all images",
        text: "Compress all images",
        completed: true,
        taskId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "6",
        title: "Implement lazy loading",
        text: "Implement lazy loading",
        completed: true,
        taskId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "SEO Improvements",
    description: "Implement SEO best practices",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    projectId: "2",
    plannedDate: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000), // 4 days in future
    checklistItems: [
      {
        id: "7",
        title: "Update meta tags",
        text: "Update meta tags",
        completed: false,
        taskId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "8",
        title: "Add structured data",
        text: "Add structured data",
        completed: false,
        taskId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Mobile Responsiveness",
    description: "Ensure website works well on all devices",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    projectId: "2",
    plannedDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    checklistItems: [
      {
        id: "9",
        title: "Test on iOS devices",
        text: "Test on iOS devices",
        completed: true,
        taskId: "5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "10",
        title: "Test on Android devices",
        text: "Test on Android devices",
        completed: false,
        taskId: "5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Setup Database",
    description: "Configure and set up the database infrastructure",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000), // 2 days in future
    checklistItems: [
      {
        id: "5",
        title: "Choose database provider",
        text: "Choose database provider",
        completed: true,
        taskId: "3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "6",
        title: "Design schema",
        text: "Design schema",
        completed: false,
        taskId: "3",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    title: "Database Schema Design",
    description: "Design the database schema for the application",
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(new Date().setDate(new Date().getDate() - 7)),
    checklistItems: [
      {
        id: "3-1",
        title: "User Model",
        text: "Design user model",
        completed: true,
        taskId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "API Endpoints",
    description: "Create API endpoints for the application",
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    projectId: "1",
    plannedDate: null,
    checklistItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Testing Strategy",
    description: "Develop a testing strategy for the application",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    projectId: "1",
    plannedDate: new Date(new Date().setDate(new Date().getDate() + 1)),
    checklistItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Deployment Setup",
    description: "Set up deployment pipeline",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(new Date().setDate(new Date().getDate() + 10)),
    checklistItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "API Development",
    description: "Develop RESTful API endpoints",
    status: TaskStatus.DONE,
    priority: TaskPriority.LOW,
    projectId: "1",
    plannedDate: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    checklistItems: [
      {
        id: "5",
        title: "User endpoints",
        text: "User endpoints",
        completed: true,
        taskId: "3",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "4",
    title: "Database Integration",
    description: "Integrate with PostgreSQL database",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    projectId: "1",
    plannedDate: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000), // 3 days in future
    checklistItems: [
      {
        id: "6",
        title: "Set up Prisma",
        text: "Set up Prisma",
        completed: false,
        taskId: "4",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "5",
    title: "Frontend Development",
    description: "Develop the user interface components",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    checklistItems: [
      {
        id: "7",
        title: "Create components",
        text: "Create components",
        completed: true,
        taskId: "5",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "8",
        title: "Implement state management",
        text: "Implement state management",
        completed: false,
        taskId: "5",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "6",
    title: "Testing",
    description: "Write unit and integration tests",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    projectId: "1",
    plannedDate: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000), // 7 days in future
    checklistItems: [
      {
        id: "9",
        title: "Set up testing framework",
        text: "Set up testing framework",
        completed: true,
        taskId: "6",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "10",
        title: "Write tests",
        text: "Write tests",
        completed: false,
        taskId: "6",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
