import {
  Project,
  Task,
  TaskStatus,
  TaskPriority,
} from "@/app/projects/[id]/types";

const now = new Date();

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Project Management App",
    description: "A comprehensive project management application",
    logo: "/project-management-logo.png",
    isMain: true,
    viewed: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    name: "Task Tracker",
    description: "Simple task tracking application",
    logo: "/task-tracker-logo.png",
    isMain: false,
    viewed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    name: "Team Collaboration Tool",
    description: "Tool for team collaboration and communication",
    logo: "/team-collab-logo.png",
    isMain: false,
    viewed: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Design User Interface",
    description: "Create wireframes and mockups for the main dashboard",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    projectId: "1",
    checklistItems: [
      {
        id: "1",
        title: "Create wireframes",
        text: "Create wireframes",
        completed: true,
        taskId: "1",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "2",
        title: "Design mockups",
        text: "Design mockups",
        completed: false,
        taskId: "1",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    title: "Implement Authentication",
    description: "Set up user authentication and authorization",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    projectId: "1",
    checklistItems: [
      {
        id: "3",
        title: "Research auth providers",
        text: "Research auth providers",
        completed: true,
        taskId: "2",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "4",
        title: "Implement login flow",
        text: "Implement login flow",
        completed: false,
        taskId: "2",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    title: "Optimize Images",
    description: "Optimize all images for better performance",
    status: TaskStatus.DONE,
    priority: TaskPriority.LOW,
    projectId: "1",
    checklistItems: [
      {
        id: "5",
        title: "Compress all images",
        text: "Compress all images",
        completed: true,
        taskId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "6",
        title: "Implement lazy loading",
        text: "Implement lazy loading",
        completed: true,
        taskId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "SEO Improvements",
    description: "Implement SEO best practices",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    projectId: "2",
    checklistItems: [
      {
        id: "7",
        title: "Update meta tags",
        text: "Update meta tags",
        completed: false,
        taskId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "8",
        title: "Add structured data",
        text: "Add structured data",
        completed: false,
        taskId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "Mobile Responsiveness",
    description: "Ensure website works well on all devices",
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    projectId: "2",
    checklistItems: [
      {
        id: "9",
        title: "Test on iOS devices",
        text: "Test on iOS devices",
        completed: true,
        taskId: "5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "10",
        title: "Test on Android devices",
        text: "Test on Android devices",
        completed: false,
        taskId: "5",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Setup Database",
    description: "Configure and set up the database infrastructure",
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    projectId: "1",
    checklistItems: [
      {
        id: "5",
        title: "Choose database provider",
        text: "Choose database provider",
        completed: true,
        taskId: "3",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "6",
        title: "Design schema",
        text: "Design schema",
        completed: false,
        taskId: "3",
        createdAt: now,
        updatedAt: now,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
